spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
      url: jdbc:mysql://local-dev.apl-golf.com:33307/batch?useSSL=false&useUnicode=true&characterEnconding=utf8
      username: root
      password: fixel12!@
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: true
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

